import AppShell from "@/components/AppShell";
import EmptyState from "@/components/EmptyState";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Gift, PackageCheck, ShieldCheck } from "lucide-react";

export default function Rewards() {
  const { isAuthenticated } = useAuth();
  const rewardsQuery = trpc.rewards.list.useQuery(undefined, { enabled: isAuthenticated });
  const redeem = trpc.rewards.redeem.useMutation();
  return <AppShell title="Ödüller" eyebrow="Puanlarını değerlendir"><section className="mb-7 rounded-3xl border border-border/80 bg-card/65 p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-teal-500/10 text-teal-700 dark:text-teal-300"><ShieldCheck className="size-5" /></span><div><h2 className="font-display text-base font-bold">Şeffaf ödül talebi</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Stok, kullanıcı limiti, puan bakiyesi ve risk kontrolleri talep sırasında sunucuda değerlendirilir.</p></div></div></section>{!isAuthenticated ? <EmptyState icon={Gift} title="Ödül kataloğu hesabınıza özel" description="Ödülleri ve talep durumlarınızı görmek için güvenli giriş yapın." action={{ label: "Giriş yap", onClick: startLogin }} /> : rewardsQuery.isLoading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map(i => <div key={i} className="h-64 animate-pulse rounded-3xl bg-muted" />)}</div> : !rewardsQuery.data?.length ? <EmptyState icon={PackageCheck} title="Ödül kataloğu hazırlanıyor" description="Yönetici aktif ödülleri yayınladığında, gerçek stok ve puan maliyetleri burada görünecek." /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rewardsQuery.data.map(reward => <article key={reward.id} className="overflow-hidden rounded-3xl border border-border/80 bg-card/75 shadow-sm"><div className="flex h-28 items-end bg-[linear-gradient(135deg,oklch(0.28_0.04_245),oklch(0.42_0.08_195))] p-4"><span className="rounded-xl bg-white/15 px-2.5 py-1 text-xs font-semibold text-white backdrop-blur">{reward.category || "Ödül"}</span></div><div className="p-5"><h2 className="font-display text-lg font-bold">{reward.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{reward.description || "Ödül ayrıntıları talep öncesinde gösterilir."}</p><div className="mt-5 flex items-center justify-between"><div><p className="text-lg font-bold text-teal-700 dark:text-teal-300">{new Intl.NumberFormat("tr-TR").format(reward.pointsCost)} puan</p><p className="text-xs text-muted-foreground">{reward.stock} adet mevcut</p></div><Button size="sm" disabled={redeem.isPending} onClick={() => redeem.mutate({ rewardId: reward.id, idempotencyKey: crypto.randomUUID() })} className="rounded-xl">Talep et</Button></div></div></article>)}</div>}</AppShell>;
}
